#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("APlus.Resource", IsApplication=true)]

namespace APlus
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int myButton = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int action_settings = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int btnGradeClass = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int btnGradeCommit = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int btnGradeIndividual = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int btnLogin = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int gridView1 = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int relativeLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int seekBarGrade = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int txtEmail = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int txtPassword = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int txtViewGrade = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int txtViewGradeLabel = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainStudent = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainTeacher = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ScanCode = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int optionsMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
